WIP: Required attr, ARIA Fields for Invalid & Error Message
ololabs/principled-forms pull request #8
Opened 2018-05-29 15:05 UTC by billpull

2018-05-29 16:23 UTC, tansongyang requested changes

2018-05-29 16:23 UTC, tansongyang commented on packages/ember-principled-forms/addon/components/form-field/template.hbs
> +      required={{required}}
Could you also add these new properties to the `{{yield}}` above? The purpose of the `yield` is to support consumers who need a completely custom template.

2018-06-13 21:35 UTC, billpull commented on packages/ember-principled-forms/addon/components/form-field/template.hbs
> +      required={{required}}
@tansongyang updated to include in `yield` and tests

2018-06-13 21:36 UTC, billpull commented on packages/ember-principled-forms/tests/integration/components/form-field-test.ts
> +    assert.equal(blockErrorSpan.textContent!.trim(), 'field is required', 'block | displays required error');
Didn't bother to `a11yAudit` here since just testing the properties can be used in block form the actual template is not accessible.

2018-06-14 01:03 UTC, chriskrycho approved these changes
This is awesome!

2018-06-14 13:09 UTC, tansongyang approved these changes

2018-06-14 14:57 UTC, merged